commands:
  - command: "tap-exchangeratesapi"
    args: "--config files/tap-config.json"
    venv: "proc_01"
    installs:
      - "pip install tap-exchangeratesapi"
  - command: "target-csv"
    args: "--config files/target-config.json"
    venv: "proc_02"
    installs:
      - "pip install target-csv"
deploy:
  cloud_provider: "aws"
  cloud_platform: "fargate"
  container_image: "singer_exchange_rates_to_csv"
  resource_group: "handoff-test"
  task: "test-exchange-rates"

envs:
  - key: "date"
    value: "2020-09-01"
