language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - python setup.py install
  - pip install -r requirements_dev.txt

script:
  - pytest -s tests/local_run_no_install
  - pytest -s tests/local_run_install
