sudo: required
dist: trusty

language: python

python:
  - "3.6"

befoer_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y python3-pygit2; fi

before_install:
  - export
  - ls /opt/python/
  - /opt/python/3.6/bin/python --version

install:
  - /opt/python/3.6/bin/python -m venv ./venv
  - source ./venv/bin/activate
  - which python
  - pip install --upgrade pip
  - pip install wheel
  - pip install --no-cache -e .
  - pip install -r requirements_dev.txt

script:
  - which python
  - pytest -s tests/unit
  - pytest -s tests/local_run_no_install
  - pytest -s tests/local_run_install
    #  - tests/install_test.sh
