tasks:
- name: generate_files
  pipeline:
  - command: cat
    args: files/in.txt
  - foreach:
    - name: do_foreach_test
      pipeline:
      - command: touch
        args: "artifacts/out_{{ _line }}.txt"

- name: verify
  pipeline:
  - command: ls
    args: "artifacts/out_*.txt"
  - command: wc
    args: -l
