version: 0.3.0

tasks:
- name: generate_files
  pipeline:
  - command: cat
    args: files/in.txt
  - foreach:
    - name: make_id_files
      pipeline:
      - command: touch
        args: "artifacts/out_{{ _line }}.txt"

- name: verify_result
  pipeline:
  - command: ls
    args: "artifacts/out_*.txt"
  - command: wc
    args: -l
