AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Bucket:
    Type: String
    Description: Bucket name
    MinLength: 3
    MaxLength: 63
    AllowedPattern: "[a-z0-9][a-z0-9-.]*"
Resources:
  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Bucket}
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Retain
