AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ResourceGroup:
    Type: String
    Description: The deploy group name
    MaxLength: 27
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9_-]*"
  GranteeAccountId:
    Type: String
    Description: The AWS account ID that gets granted to assume the role
    MaxLength: 27
    AllowedPattern: "[0-9][0-9]*"
  ExternalId:
    Type: String
    Description: The external ID
    MaxLength: 27
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9_-]*"
Resources:
  FargateDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub handoff-FargateDeployRole-${ResourceGroup}-${GranteeAccountId}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${GranteeAccountId}:root
          Action:
            - sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId: !Sub ${ExternalId}
      Path: /
      Policies:
        - PolicyName: !Sub handoff-FargateDeployRole-${ResourceGroup}-${GranteeAccountId}
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
              - cloudformation:CancelUpdateStack
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStackEvents
              - cloudformation:DescribeStackResources
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              Resource: !Sub "arn:aws:cloudformation:::*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - ec2:AssociateRouteTable
              - ec2:AttachInternetGateway
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:CreateInternetGateway
              - ec2:CreateRoute
              - ec2:CreateRouteTable
              - ec2:CreateSecurityGroup
              - ec2:CreateSubnet
              - ec2:CreateVpc
              - ec2:DeleteInternetGateway
              - ec2:DeleteRoute
              - ec2:DeleteRouteTable
              - ec2:DeleteSecurityGroup
              - ec2:DeleteSecurityGroup
              - ec2:DeleteSubnet
              - ec2:DeleteVpc
              - ec2:DescribeAccountAttributes
              - ec2:DescribeAvailabilityZones
              - ec2:DescribeInternetGateways
              - ec2:DescribeRouteTables
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcs
              - ec2:DetachInternetGateway
              - ec2:DisassociateRouteTable
              - ec2:ModifySubnetAttribute
              - ec2:ModifyVpcAttribute
              - ec2:RevokeSecurityGroupEgress
              - ec2:RevokeSecurityGroupEgress
              Resource: !Sub "arn:aws:ec2:::*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchDeleteImage
              - ecr:BatchGetImage
              - ecr:CompleteLayerUpload
              - ecr:CreateRepository
              - ecr:DeleteLifecyclePolicy
              - ecr:DeleteRepository
              - ecr:DeleteRepositoryPolicy
              - ecr:DescribeImageScanFindings
              - ecr:DescribeImages
              - ecr:DescribeRepositories
              - ecr:GetAuthorizationToken
              - ecr:GetDownloadUrlForLayer
              - ecr:GetLifecyclePolicy
              - ecr:GetLifecyclePolicyPreview
              - ecr:GetRepositoryPolicy
              - ecr:InitiateLayerUpload
              - ecr:ListImages
              - ecr:ListTagsForResource
              - ecr:PutImage
              - ecr:PutImageScanningConfiguration
              - ecr:PutImageTagMutability
              - ecr:PutLifecyclePolicy
              - ecr:StartImageScan
              - ecr:StartLifecyclePolicyPreview
              - ecr:TagResource
              - ecr:UntagResource
              - ecr:UploadLayerPart
              Resource: !Sub "arn:aws:ecr:::*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - ecs:CreateCluster
              - ecs:DeleteCluster
              - ecs:DeregisterContainerInstance
              - ecs:DeregisterTaskDefinition
              - ecs:DescribeClusters
              - ecs:DescribeTasks
              - ecs:Poll
              - ecs:RegisterContainerInstance
              - ecs:RegisterTaskDefinition
              - ecs:RunTask
              - ecs:StartTask
              - ecs:StopTask
              - ecs:ListTasks
              Resource: !Sub "arn:aws:ecs:::*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - events:DeleteRule
              - events:PutRule
              - events:PutTargets
              - events:RemoveTargets
              Resource: !Sub "arn:aws:events:::*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - iam:CreateRole
              - iam:CreateServiceLinkedRole
              - iam:DeleteRole
              - iam:DeleteRolePolicy
              - iam:GetRole
              - iam:GetRolePolicy
              - iam:ListRoles
              - iam:PassRole
              - iam:PutRolePolicy
              Resource: !Sub "arn:aws:iam:::role/*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - logs:CreateLogGroup
              - logs:DeleteLogGroup
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:FilterLogEvents
              - logs:GetLogDelivery
              - logs:GetLogEvents
              - logs:GetLogGroupFields
              - logs:GetLogRecord
              - logs:GetQueryResults
              - logs:PutRetentionPolicy
              - logs:StartQuery
              - logs:StopQuery
              - logs:TestMetricFilter
              Resource: !Sub "arn:aws:logs:::*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - s3:CreateBucket
              - s3:DeleteBucket
              - s3:DeleteObject
              - s3:GetObject
              - s3:ListBucket
              - s3:PutBucketPublicAccessBlock
              - s3:PutEncryptionConfiguration
              - s3:PutObject
              Resource: !Sub "arn:aws:s3:::*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - ssm:DeleteParameter
              - ssm:DeleteParameters
              - ssm:DescribeParameters
              - ssm:GetParameter
              - ssm:GetParameterHistory
              - ssm:GetParameters
              - ssm:GetParametersByPath
              - ssm:PutParameter
              Resource: !Sub "arn:aws:ssm:::*handoff-${ResourceGroup}*"
            - Effect: Allow
              Action:
              - sts:AssumeRole
              Resource: !Sub "arn:aws:sts:::*handoff-${ResourceGroup}*"
