ARTIFACTS_DIR = "artifacts"
CONFIG_DIR = "config"
FILES_DIR = "files"
PROJECT_FILE = "project.yml"

BUCKET_CURRENT_PREFIX = "last"
BUCKET_ARCHIVE_PREFIX = "runs"

# environment variable keys (not the values)
BUCKET = "BUCKET"
DOCKER_IMAGE = "DOCKER_IMAGE"
IMAGE_DOMAIN = "IMAGE_DOMAIN"
IMAGE_VERSION = "IMAGE_VERSION"
RESOURCE_GROUP = "RESOURCE_GROUP"
TASK = "TASK"

ADMIN_ENVS = [BUCKET, DOCKER_IMAGE,
              # IMAGE_DOMAIN, IMAGE_VERSION,
              RESOURCE_GROUP, TASK]
