version: 0.3
description: Fetch foreign exchange rates

installs:
- venv: tap
  command: pip install tap-exchangeratehost
- venv: target
  command: pip install target-csv

vars:
- key: base_currency
  value: USD

tasks:
- name: fetch_exchange_rates
  description: Fetch exchange rates
  pipeline:
  - command: tap-exchangeratehost
    args: --config files/tap-config.json
    venv: tap
  - fork:
    - name: wide-format
      pipeline:
      - command: target-csv
        args: --config files/target-config.json
        venv: target
    - name: long-format
      pipeline:
      - command: python3
        args: files/convert_to_long_format.py
      - command: target-csv
        args: --config files/target-config.json
        venv: target

deploy:
  cloud_provider: aws
  cloud_platform: fargate
  resource_group: handoff-etl
  container_image: tap-exchangeratehost-target-csv
  task: exchange-rates

schedule:
  target_id: 1
  cron: "0 0 * * ? *"
  envs: []
