commands:
  - command: "tap-exchangeratesapi"
    args: "--config config/tap-config.json"
    venv: "proc_01"
    installs:
      - "pip install tap-exchangeratesapi"
  - command: "files/stats_collector.py"
    venv: "proc_01"
  - command: "target-csv"
    venv: "proc_02"
    installs:
      - "pip install target-csv"
