# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

# Repo root on the path so ``automodule:: handoff.*`` resolves when building
# from a source checkout (was '../handoff', which put the package's *inside*
# on the path and could not import ``handoff`` as a package).
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------

project = 'handoff'
copyright = '2020, ANELEN'
author = 'ANELEN'


def _get_version():
    """Resolve the version dynamically.

    Prefer installed package metadata, fall back to reading pyproject.toml.
    This was previously hardcoded ('0.3.0'), so the published docs kept
    advertising 0.3.0 across every release up to 0.4.3.
    """
    try:
        from importlib.metadata import version as _version

        return _version("handoff")
    except Exception:
        pass
    try:
        import tomllib
    except ModuleNotFoundError:  # Python < 3.11
        return "0.0.0"
    pyproject = os.path.join(os.path.dirname(__file__), os.pardir, "pyproject.toml")
    try:
        with open(pyproject, "rb") as fh:
            return tomllib.load(fh)["project"]["version"]
    except Exception:
        return "0.0.0"


# The short X.Y version
version = _get_version()
# The full version, including alpha/beta/rc tags
release = version


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'myst_parser',
    'sphinx.ext.autodoc',
]

# myst-parser replaces recommonmark (archived) + m2r (unmaintained) and renders
# tables natively, so sphinx_markdown_tables is no longer needed.
myst_enable_extensions = [
    'colon_fence',
    'deflist',
]
# Match the old recommonmark auto_toc_tree behavior closely enough for the
# existing docs, and keep header anchors resolvable from markdown links.
myst_heading_anchors = 3

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'handoffdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'handoff.tex', 'handoff Documentation',
     'ANELEN', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'handoff', 'handoff Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'handoff', 'handoff Documentation',
     author, 'handoffcloud', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# NOTE: the previous setup() registered recommonmark's AutoStructify, m2r's
# ``mdinclude`` directive, and an ``autodoc-process-docstring`` hook that ran
# docstrings through m2r. All of that is dropped with the move to myst-parser:
#   - markdown files are parsed natively (see source_suffix / extensions),
#   - ``.. mdinclude:: x.md`` is replaced by
#     ``.. include:: x.md`` + ``:parser: myst_parser.sphinx_``,
#   - docstrings are now rendered as reStructuredText by autodoc.
# It also referenced an undefined ``github_doc_root``, which would have raised
# NameError as soon as a markdown link needed resolving.
