#!/bin/bash

echo Welcome to handoff tutorial

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ ! -d $PROJECT_DIR/03_exchange_rates ]; then
    echo The project does not exist
    exit 1
fi

IFS=$'\n' read -r -d '' -a COMMANDS < <( ls $PROJECT_DIR/scripts |grep -v colors && printf '\0' )

echo "This tutorial has ${#COMMANDS[@]} short (< 5min each) parts:"
i=1
for s in `ls $PROJECT_DIR/scripts |grep -v colors`; do echo "- [$i] $s"; i=$((i+1)); done

read -p "Which one would you like to do? (ctl-c to exit) " -n 1
while [[ ( "$REPLY" -lt 1 || "$REPLY" -gt ${#COMMANDS[@]} ) ]]
do
    echo Hmm...you did not enter the number expected. Plesae try again.
    read -p "> "
done

echo

c=$(($REPLY-1))
$PROJECT_DIR/scripts/${COMMANDS[$c]}
