#!/bin/bash
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/.."
source $PROJECT_DIR/scripts/funcs

if [ ! -d $PROJECT_DIR/03_exchange_rates ]; then
echo "
The project does not exist...try running
    handoff quick_start start
in a new directory.
"
    exit 1
fi

cd $PROJECT_DIR

echo "
Welcome to module 01_run_local
We will learn how to run handoff local test using a project 01_word_count
"

echo "Ready? (ctl-c to quit anytime)"

Prompt

echo Each project directory contains:
echo
for i in `ls 01_word_count`; do echo - $i; done

Prompt

echo project.yml looks like:
Cat "01_word_count/project.yml" $DIM

Prompt

echo commands lists the commands and arguments. env lists the environment varaibles.

echo "
This example from 01_word_count runs a command line equivalent of:

    cat ./files/the_great_dictator_speech.txt | wc -w
"

echo Now let\'s run. Try entering this command below:
Command "handoff --project 01_word_count --workspace workspace run local"

echo If you see the output that looks like:

echo -e $DIM
echo "INFO - 2020-08-03 04:51:01,971 - handoff.config - Reading configurations from 01_word_count/project.yml"
echo "..."
echo "INFO - 2020-08-03 04:51:02,690 - handoff.config - Processed in 0:00:00.005756"
echo -e $RESET

echo Then great! You just ran the first local test. It created a workspace directory that looks like:
echo
for i in `ls workspace`; do echo - $i; done
echo And the word count is stored at workspace/artifacts/state. Here is the content:
echo
cat workspace/artifacts/state
echo

Prompt

echo "
By the way, the example text is from the awesome speech by Charlie Chaplin\'s in the movie the Great Dictator.
Here is a link to the famous speech scene. Check out on YouTube: https://www.youtube.com/watch?v=J7GY1Xg6X20
"

Prompt

echo And here is the first few paragraphs of the text:
echo -e $BLUE
head -n 4 01_word_count/files/the_great_dictator_speech.txt
echo -e $RESET

Prompt

echo Now to the second example. This time project.yml looks like:
Cat 02_collect_stats/project.yml $DIM

Prompt

echo "
...which is shell equivalent to

    cat ./files/the_great_dictator_speech.txt | python ./files/stats_collector.py | wc -w
"

echo "
The script for the second command stats_collector.py can be found in 02_collect_stats/files directory
and it is a Python script that looks like:
"

Prompt

Cat "02_collect_stats/files/stats_collector.py" $DIM

echo "
The script reads from stdin and counts the lines while passing the raw input to stdout.
The raw text is then processed by the third command (wc -w) and it conts the number of words.
"

Prompt

echo Now let\'s run. Try entering this command below:
Command "handoff --project 02_collect_stats --workspace workspace run local"

echo Let\'s check out the contents of the second command:

Prompt

Cat "workspace/artifacts/collect_stats.json" $DIM

Prompt

echo Great. This concludes this section of the tutorial.

Prompt

Thanks

echo "
In the next section, we will try pullin the currency exchange rate data.
You will also learn how to create Python virtual enviroments for each command and pip-install commands.
"

Continue

$PROJECT_DIR/scripts/02_exchange_rates
