#!/bin/bash
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/.."

if [ ! -d $PROJECT_DIR/03_exchange_rates ]; then
echo "
The project does not exist...try running
    handoff quick_start start
in a new directory.
" # echo
    exit 1
fi

cd $PROJECT_DIR
source scripts/colors

echo "
Welcome to module 03_set_up_aws_account!
handoff helps you to deploy the task in the cloud computing services.
In this tutorial series, our goal is to deploy the currency exchange
rates task to AWS Fargate. https://aws.amazon.com/fargate/
Before we can deploy, we need to set up the account and roles.
" # echo

echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt

echo "
Do I need a credit card to use AWS? How much does it cost?
Yes, you need a credit card. But it won\'t cost a cup of coffee for this tutorial.
Some of the AWS services we use comes with a Free Tier and you won\'t be
charged for the eligible usage.

Learn more about Free Tier: https://aws.amazon.com/free
"

echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt

echo "
Here is the complete list of the services we use:

- Simple Storage Service, free with Free Tier usage:
    https://aws.amazon.com/s3/pricing/#AWS_Free_Tier
- Fargate, almost free:
    Price calculator http://fargate-pricing-calculator.site.s3-website-us-east-1.amazonaws.com/
    (We use 0.25vCPU with 0.5GB RAM for less than 5 minutes.)
- Systems Management Parameter Store, free (Standard tier):
    Pricing: https://aws.amazon.com/systems-manager/pricing/#Parameter_Store
- Elastic Container Registry, free for 500MB per month
    Pricing: https://aws.amazon.com/ecr/pricing/
"

echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt

a=`cat ~/.aws/credentials | grep "\[default\]"`
if [[ -f ~/.aws/credentials && ! -z "$a" ]]
then
echo "
It looks like you already have AWS CLI set up. You may just scan through
the rest of the tutorial.
"
echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt
fi

echo "
AWS sign up is easy. Just go to:

    https://aws.amazon.com/free
    
and complete the sign up process.

The rest of the tutorial assumes that you have an active AWS account.
"

echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt

echo "
If you haven't, install AWS CLI (command line interface):

    https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html
"

echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt

echo "
Also generate access key ID and secret access key by following:

    https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html#cli-configure-quickstart-creds

Take note of the values that looks like:

- Access key ID: AKIAIOSFODNN7EXAMPLE
- Secret access key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

The only time that you can view or download the secret access key is when you
create the keys. You cannot recover them later. So keep a local copy.
"

echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt

echo "
Last step before going back to handoff. From the console, run:

    aws configure --profile default

Enter Access key ID and Secret access key you created in the last step.

For region, use one of these keys (for USA users, us-east-1 would do):

- ap-northeast-1
- ap-northeast-2
- ap-south-1
- ap-southeast-1
- ap-southeast-2
- ca-central-1
- eu-central-1
- eu-north-1
- eu-west-1
- eu-west-2
- eu-west-3
- sa-east-1
- us-east-1
- us-east-2
- us-west-1
- us-west-2

Learn more about AWS profile here:
    https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html
"

echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt

echo Great. This concludes this section of the tutorial.

echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt

echo Thanks for completing this section of tutorial. Oh, before you go,
echo do you use Twitter? Can you do me a favor and let your fellow engineers know about handoff?
echo -e $GREEN; read -p "Open your browser to auto-draft your tweet? (y/N) " -n 1 -r; echo -e $RESET  # Prompt
echo    # (optional) move to a new line

URL="https://twitter.com/intent/tweet?text=Engineers%21%20This%20is%20awesome.%20Just%20do%0Apip%20install%20handoff%0Aand%0Ahandoff%20quick_start%20start%0AAnd%20see%20what%20happens.%20https%3A%2F%2Fdev.handoff.cloud"
if [[ $REPLY =~ ^[Yy]$ ]]
then
open $URL
else
echo "OK! In case you change your mind, here is the link to auto-draft your tweets (you can edit before you tweet)"
echo -e $GREEN$URL$RESET
fi
echo

echo "
Now that we have set up the AWS account, let's store the configurations
in the cloud.
"

echo -e $GREEN; read -p "Continue? (Y/n) " -n 1 -r; echo -e $RESET  # Prompt
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Nn]$ ]]
then
    echo "OK!"
    echo "Remember that you can continue by"
    echo -e $GREEN    $PROJECT_DIR/begin$RESET
    echo
    echo "bye!"
    exit 0
fi

$PROJECT_DIR/scripts/04_run_remote_config
