#!/bin/bash
if [[ -z $2 ]];then HEADTAIL_LIMIT=0; else HEADTAIL_LIMIT=$2;fi
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd ..
source scripts/funcs

for i in `ls scripts/aws_get_started | grep -v funcs`;
do
export SCRIPT=$i
./scripts/auto_run auto 10
done
