#!/bin/bash

export RESET="\033[0m"
export RED="\033[91m"
export GREEN="\033[32m"
export BLUE="\033[34m"
export YELLOW="\033[33m"
export BLINK="\033[5m"
export DIM="\033[2m"

Prompt() {
echo -e $GREEN $BLINK; read -p "> " -n 1 -r; echo -e $RESET  # Prompt
if [[ $REPLY =~ ^[Qq]$ ]]
then
    echo "bye!"
    exit 0
fi
}

ListDir() {
echo -e $2
for i in `ls $1`; do echo - $i; done
echo -e $RESET
}

Cat() {
echo -e $2; cat $1; echo -e $RESET
}

Choose() {
echo $1
IFS=$'\n' read -r -d '' -a OPTIONS < <( eval $1 )
# IFS=$'\n' read -r -d '' -a OPTIONS < <( ls $PROJECT_DIR/scripts | grep -v funcs && printf '\0' )
i=1
for s in ${OPTIONS[@]}; do echo "- [$i] $s"; i=$((i+1)); done

read -p "> " -n 1
while [[ ( "$REPLY" -lt 1 || "$REPLY" -gt ${#OPTIONS[@]} ) ]]
do
    echo Hmm...you did not enter the number expected. Plesae try again.
    read -p "> "
done
echo
CHOICE=$(($REPLY-1))
}

Command() {
echo -e $GREEN    $1$RESET
echo
read -p "> "
while [[ ! $REPLY = $1 ]]
do
    echo Hmm...you did not enter correctly, try again.
    read -p "> "
done
echo -e $DIM; $1; echo -e $RESET
}

CheckAws() {
a=`cat ~/.aws/credentials`
if [[ ! -f ~/.aws/credentials ]]
then
echo "
Hmm...it looks like you don't have ~/.aws/credentials file set up from
the previous tutorial. 
"
echo -e $GREEN; read -p "Woud you like to go back? (Y/n) " -n 1 -r; echo -e $RESET  # Prompt
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Nn]$ ]]
then
    echo "OK!"
    echo
    $PROJECT_DIR/scripts/03_set_up_aws_account
    exit 0
fi
fi
}

ChooseAwsProfile() {
if [[ -z AWS_PROFILE ]]
then
echo "
First we tell AWS which account profile we want to use. Which one would you like to use?
"
Choose 'cat ~/.aws/credentials |grep "\[" | sed "s/\[\(.*\)]/\1/" && printf "\0"'
echo "
Running this to select the profile:
"
Command "export AWS_PROFILE=${OPTIONS[$CHOICE]}"
fi
}

Thanks() {
echo "
Thanks for completing this section of tutorial. Oh, before you go,
do you use Twitter? Can you do me a favor and let your fellow engineers know about handoff?
"

echo -e $GREEN; read -p "Open your browser to auto-draft your tweet? (y/N) " -n 1 -r; echo -e $RESET  # Prompt
echo    # (optional) move to a new line

URL="https://twitter.com/intent/tweet?text=Engineers%21%20This%20is%20awesome.%20Just%20do%0Apip%20install%20handoff%0Aand%0Ahandoff%20quick_start%20start%0AAnd%20see%20what%20happens.%20https%3A%2F%2Fdev.handoff.cloud"
if [[ $REPLY =~ ^[Yy]$ ]]
then
open $URL
else
echo "OK! In case you change your mind, here is the link to auto-draft your tweets (you can edit before you tweet)"
echo -e $GREEN$URL$RESET
fi
}

Continue () {
echo -e $GREEN; read -p "Continue? (Y/n) " -n 1 -r; echo -e $RESET  # Prompt
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Nn]$ ]]
then
    echo "OK!"
    echo "Remember that you can continue by"
    echo -e $GREEN    $PROJECT_DIR/begin$RESET
    echo
    echo "bye!"
    exit 0
fi
}
